<?php
/**
 * Params15Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CBRAIN API
 *
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Params15Test Class Doc Comment
 *
 * @category    Class */
// * @description Params15
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Params15Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Params15"
     */
    public function testParams15()
    {

    }

    /**
     * Test attribute "data_provider_id_for_mv_cp"
     */
    public function testPropertyDataProviderIdForMvCp()
    {

    }

    /**
     * Test attribute "crush_destination"
     */
    public function testPropertyCrushDestination()
    {

    }

    /**
     * Test attribute "file_ids"
     */
    public function testPropertyFileIds()
    {

    }

}
