<?php
/**
 * UserTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CBRAIN API
 *
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UserTest Class Doc Comment
 *
 * @category    Class */
// * @description User
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "User"
     */
    public function testUser()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "login"
     */
    public function testPropertyLogin()
    {

    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {

    }

    /**
     * Test attribute "password_confirmation"
     */
    public function testPropertyPasswordConfirmation()
    {

    }

    /**
     * Test attribute "full_name"
     */
    public function testPropertyFullName()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "site_id"
     */
    public function testPropertySiteId()
    {

    }

    /**
     * Test attribute "last_connected_at"
     */
    public function testPropertyLastConnectedAt()
    {

    }

    /**
     * Test attribute "account_locked"
     */
    public function testPropertyAccountLocked()
    {

    }

}
