<?php
/**
 * TagsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CBRAIN API
 *
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TagsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TagsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for tagsGet
     *
     * Get a list of the tags currently in CBRAIN..
     *
     */
    public function testTagsGet()
    {

    }

    /**
     * Test case for tagsIdDelete
     *
     * Delete a tag..
     *
     */
    public function testTagsIdDelete()
    {

    }

    /**
     * Test case for tagsIdGet
     *
     * Get one tag..
     *
     */
    public function testTagsIdGet()
    {

    }

    /**
     * Test case for tagsIdPut
     *
     * Update a tag..
     *
     */
    public function testTagsIdPut()
    {

    }

    /**
     * Test case for tagsPost
     *
     * Create a tag..
     *
     */
    public function testTagsPost()
    {

    }

}
