<?php
/**
 * Params19
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CBRAIN API
 *
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Params19 Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Params19 implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'params_19';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'tool_config_id' => 'int',
        'cbrain_task' => '\Swagger\Client\Model\CbrainTask',
        'authenticity_token' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'tool_config_id' => 'tool_config_id',
        'cbrain_task' => 'cbrain_task',
        'authenticity_token' => 'authenticity_token'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'tool_config_id' => 'setToolConfigId',
        'cbrain_task' => 'setCbrainTask',
        'authenticity_token' => 'setAuthenticityToken'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'tool_config_id' => 'getToolConfigId',
        'cbrain_task' => 'getCbrainTask',
        'authenticity_token' => 'getAuthenticityToken'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['tool_config_id'] = isset($data['tool_config_id']) ? $data['tool_config_id'] : null;
        $this->container['cbrain_task'] = isset($data['cbrain_task']) ? $data['cbrain_task'] : null;
        $this->container['authenticity_token'] = isset($data['authenticity_token']) ? $data['authenticity_token'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets tool_config_id
     * @return int
     */
    public function getToolConfigId()
    {
        return $this->container['tool_config_id'];
    }

    /**
     * Sets tool_config_id
     * @param int $tool_config_id The ID number of the Tool Config to be used to launch the Task.
     * @return $this
     */
    public function setToolConfigId($tool_config_id)
    {
        $this->container['tool_config_id'] = $tool_config_id;

        return $this;
    }

    /**
     * Gets cbrain_task
     * @return \Swagger\Client\Model\CbrainTask
     */
    public function getCbrainTask()
    {
        return $this->container['cbrain_task'];
    }

    /**
     * Sets cbrain_task
     * @param \Swagger\Client\Model\CbrainTask $cbrain_task
     * @return $this
     */
    public function setCbrainTask($cbrain_task)
    {
        $this->container['cbrain_task'] = $cbrain_task;

        return $this;
    }

    /**
     * Gets authenticity_token
     * @return string
     */
    public function getAuthenticityToken()
    {
        return $this->container['authenticity_token'];
    }

    /**
     * Sets authenticity_token
     * @param string $authenticity_token The token returned by /session/new
     * @return $this
     */
    public function setAuthenticityToken($authenticity_token)
    {
        $this->container['authenticity_token'] = $authenticity_token;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


