<?php
/**
 * TasksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CBRAIN API
 *
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TasksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TasksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for tasksGet
     *
     * Get the list of Tasks..
     *
     */
    public function testTasksGet()
    {

    }

    /**
     * Test case for tasksIdDelete
     *
     * Deletes a Task.
     *
     */
    public function testTasksIdDelete()
    {

    }

    /**
     * Test case for tasksIdGet
     *
     * Get information on a Task..
     *
     */
    public function testTasksIdGet()
    {

    }

    /**
     * Test case for tasksIdPut
     *
     * Update information on a Task..
     *
     */
    public function testTasksIdPut()
    {

    }

    /**
     * Test case for tasksPost
     *
     * Create a new Task..
     *
     */
    public function testTasksPost()
    {

    }

}
