<?php
/**
 * Params5
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CBRAIN API
 *
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Params5 Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Params5 implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'params_5';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'basenames' => 'string[]',
        'as_user_id' => 'int',
        'delete' => 'bool',
        'authenticity_token' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'basenames' => 'basenames',
        'as_user_id' => 'as_user_id',
        'delete' => 'delete',
        'authenticity_token' => 'authenticity_token'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'basenames' => 'setBasenames',
        'as_user_id' => 'setAsUserId',
        'delete' => 'setDelete',
        'authenticity_token' => 'setAuthenticityToken'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'basenames' => 'getBasenames',
        'as_user_id' => 'getAsUserId',
        'delete' => 'getDelete',
        'authenticity_token' => 'getAuthenticityToken'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['basenames'] = isset($data['basenames']) ? $data['basenames'] : null;
        $this->container['as_user_id'] = isset($data['as_user_id']) ? $data['as_user_id'] : null;
        $this->container['delete'] = isset($data['delete']) ? $data['delete'] : null;
        $this->container['authenticity_token'] = isset($data['authenticity_token']) ? $data['authenticity_token'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['basenames'] === null) {
            $invalid_properties[] = "'basenames' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['basenames'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets basenames
     * @return string[]
     */
    public function getBasenames()
    {
        return $this->container['basenames'];
    }

    /**
     * Sets basenames
     * @param string[] $basenames An array containing the filenames to unregister.
     * @return $this
     */
    public function setBasenames($basenames)
    {
        $this->container['basenames'] = $basenames;

        return $this;
    }

    /**
     * Gets as_user_id
     * @return int
     */
    public function getAsUserId()
    {
        return $this->container['as_user_id'];
    }

    /**
     * Sets as_user_id
     * @param int $as_user_id The ID of the user to unregister files as.
     * @return $this
     */
    public function setAsUserId($as_user_id)
    {
        $this->container['as_user_id'] = $as_user_id;

        return $this;
    }

    /**
     * Gets delete
     * @return bool
     */
    public function getDelete()
    {
        return $this->container['delete'];
    }

    /**
     * Sets delete
     * @param bool $delete Specifies to delete the files once they are unregistered.
     * @return $this
     */
    public function setDelete($delete)
    {
        $this->container['delete'] = $delete;

        return $this;
    }

    /**
     * Gets authenticity_token
     * @return string
     */
    public function getAuthenticityToken()
    {
        return $this->container['authenticity_token'];
    }

    /**
     * Sets authenticity_token
     * @param string $authenticity_token The token returned by /session/new
     * @return $this
     */
    public function setAuthenticityToken($authenticity_token)
    {
        $this->container['authenticity_token'] = $authenticity_token;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


