<?php
/**
 * CbrainTaskTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CBRAIN API
 *
 * Interface to control CBRAIN operations
 *
 * OpenAPI spec version: 4.5.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CbrainTaskTest Class Doc Comment
 *
 * @category    Class */
// * @description CbrainTask
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CbrainTaskTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CbrainTask"
     */
    public function testCbrainTask()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "batch_id"
     */
    public function testPropertyBatchId()
    {

    }

    /**
     * Test attribute "cluster_jobid"
     */
    public function testPropertyClusterJobid()
    {

    }

    /**
     * Test attribute "cluster_workdir"
     */
    public function testPropertyClusterWorkdir()
    {

    }

    /**
     * Test attribute "params"
     */
    public function testPropertyParams()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "bourreau_id"
     */
    public function testPropertyBourreauId()
    {

    }

    /**
     * Test attribute "prerequisites"
     */
    public function testPropertyPrerequisites()
    {

    }

    /**
     * Test attribute "share_wd_tid"
     */
    public function testPropertyShareWdTid()
    {

    }

    /**
     * Test attribute "run_number"
     */
    public function testPropertyRunNumber()
    {

    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {

    }

    /**
     * Test attribute "tool_config_id"
     */
    public function testPropertyToolConfigId()
    {

    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {

    }

    /**
     * Test attribute "rank"
     */
    public function testPropertyRank()
    {

    }

    /**
     * Test attribute "results_data_provider_id"
     */
    public function testPropertyResultsDataProviderId()
    {

    }

    /**
     * Test attribute "workdir_archived"
     */
    public function testPropertyWorkdirArchived()
    {

    }

    /**
     * Test attribute "workdir_archive_userfile_id"
     */
    public function testPropertyWorkdirArchiveUserfileId()
    {

    }

}
